// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"
)

const addJob = `-- name: AddJob :exec
INSERT INTO jobs (id, schedule, message) VALUES (?, ?, ?)
`

type AddJobParams struct {
	ID       string
	Schedule string
	Message  string
}

func (q *Queries) AddJob(ctx context.Context, arg AddJobParams) error {
	_, err := q.db.ExecContext(ctx, addJob, arg.ID, arg.Schedule, arg.Message)
	return err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ?
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteJob, id)
	return err
}

const listJobs = `-- name: ListJobs :many
SELECT id, schedule, message FROM jobs
`

func (q *Queries) ListJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(&i.ID, &i.Schedule, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
