// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Job struct {
	ID       string
	Schedule string
	Message  string
}

type SchemaMigration struct {
	Version int64
}
