// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
)

const addProject = `-- name: AddProject :exec
INSERT INTO projects (name, path) VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET path = excluded.path
`

type AddProjectParams struct {
	Name string
	Path string
}

func (q *Queries) AddProject(ctx context.Context, arg AddProjectParams) error {
	_, err := q.db.ExecContext(ctx, addProject, arg.Name, arg.Path)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, name)
	return err
}

const getProject = `-- name: GetProject :one
SELECT name, path FROM projects WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var i Project
	err := row.Scan(&i.Name, &i.Path)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT name, path FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.Name, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
