// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
)

const addProject = `-- name: AddProject :exec
INSERT INTO projects (name, path) VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET path = excluded.path
`

type AddProjectParams struct {
	Name string
	Path string
}

func (q *Queries) AddProject(ctx context.Context, arg AddProjectParams) error {
	_, err := q.db.ExecContext(ctx, addProject, arg.Name, arg.Path)
	return err
}

const addProjectEnv = `-- name: AddProjectEnv :exec
INSERT INTO project_env (project_name, secret_key, env_var) VALUES (?, ?, ?)
ON CONFLICT (project_name, secret_key) DO UPDATE SET env_var = excluded.env_var
`

type AddProjectEnvParams struct {
	ProjectName string
	SecretKey   string
	EnvVar      string
}

func (q *Queries) AddProjectEnv(ctx context.Context, arg AddProjectEnvParams) error {
	_, err := q.db.ExecContext(ctx, addProjectEnv, arg.ProjectName, arg.SecretKey, arg.EnvVar)
	return err
}

const deleteAllProjectEnv = `-- name: DeleteAllProjectEnv :exec
DELETE FROM project_env WHERE project_name = ?
`

func (q *Queries) DeleteAllProjectEnv(ctx context.Context, projectName string) error {
	_, err := q.db.ExecContext(ctx, deleteAllProjectEnv, projectName)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE name = ?
`

func (q *Queries) DeleteProject(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, name)
	return err
}

const deleteProjectEnv = `-- name: DeleteProjectEnv :exec
DELETE FROM project_env WHERE project_name = ? AND secret_key = ?
`

type DeleteProjectEnvParams struct {
	ProjectName string
	SecretKey   string
}

func (q *Queries) DeleteProjectEnv(ctx context.Context, arg DeleteProjectEnvParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectEnv, arg.ProjectName, arg.SecretKey)
	return err
}

const getProject = `-- name: GetProject :one
SELECT name, path FROM projects WHERE name = ?
`

func (q *Queries) GetProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, name)
	var i Project
	err := row.Scan(&i.Name, &i.Path)
	return i, err
}

const listProjectEnv = `-- name: ListProjectEnv :many
SELECT secret_key, env_var FROM project_env WHERE project_name = ? ORDER BY secret_key
`

type ListProjectEnvRow struct {
	SecretKey string
	EnvVar    string
}

func (q *Queries) ListProjectEnv(ctx context.Context, projectName string) ([]ListProjectEnvRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectEnv, projectName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectEnvRow
	for rows.Next() {
		var i ListProjectEnvRow
		if err := rows.Scan(&i.SecretKey, &i.EnvVar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT name, path FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(&i.Name, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
